#!/usr/bin/env node
// Downloads the web fonts the app needs and rewrites them as a local stylesheet,
// so the bundle renders with no network access.
//
//   node tools/fetch-fonts.mjs
//
// Material Symbols is subsetted to exactly the icons referenced in the markup and
// in app.js (the full variable font is several megabytes). Re-run this script after
// introducing a new icon, otherwise it renders as its literal ligature name.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const WWW = join(ROOT, 'assets/www');
const FONT_DIR = join(WWW, 'fonts');

// Google Fonts serves woff2 only to browsers it recognises.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

async function iconNames() {
  const sources = await Promise.all(
    ['index.html', 'app.js'].map((f) => readFile(join(WWW, f), 'utf8')),
  );
  const found = new Set();
  for (const src of sources) {
    for (const m of src.matchAll(/material-symbols-outlined[^>]*>([a-z_]+)/g)) {
      found.add(m[1]);
    }
  }
  return [...found].sort();
}

async function fetchCss(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.text();
}

// Pulls every remote woff2 out of a Google Fonts stylesheet, saves it locally and
// rewrites the src() to point at the saved copy.
async function localise(css, filePrefix) {
  const urls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+)\)/g)].map((m) => m[1]))];
  let out = css;
  let i = 0;

  for (const url of urls) {
    const res = await fetch(url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
    const bytes = Buffer.from(await res.arrayBuffer());
    const name = `${filePrefix}-${i++}.woff2`;
    await writeFile(join(FONT_DIR, name), bytes);
    out = out.replaceAll(url, name);
    console.log(`  ${name.padEnd(28)} ${(bytes.length / 1024).toFixed(1)} KB`);
  }
  return out;
}

async function main() {
  await mkdir(FONT_DIR, { recursive: true });

  console.log('Geist:');
  const geist = await localise(
    await fetchCss('https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap'),
    'geist',
  );

  const icons = await iconNames();
  console.log(`Material Symbols (${icons.length} icons: ${icons.join(', ')}):`);
  const symbols = await localise(
    await fetchCss(
      'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined' +
        ':opsz,wght,FILL,GRAD@24,100..700,0..1,0' +
        `&icon_names=${icons.join(',')}&display=block`,
    ),
    'material-symbols',
  );

  const header =
    '/* Generated by tools/fetch-fonts.mjs — do not edit by hand.\n' +
    `   Material Symbols is subsetted to: ${icons.join(', ')} */\n\n`;

  await writeFile(join(FONT_DIR, 'fonts.css'), header + geist + '\n' + symbols);
  console.log('\nWrote assets/www/fonts/fonts.css');
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
