#!/usr/bin/env node
// Generates assets/www/sw.js: `node tools/make-sw.mjs`.
//
// The previous service worker carried a hand-written list of files, five of which
// did not exist. cache.addAll rejects atomically, so its install failed every single
// time and it never cached anything at all. This one is generated from what is
// actually in the bundle, and its cache name is a hash of those files' contents, so
// a deploy invalidates the old cache without anyone having to remember to bump it.

import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const WWW = join(ROOT, 'assets/www');
const SW = join(WWW, 'sw.js');

// Design mockups and the worker itself are not part of the running app.
const SKIP = new Set(['sw.js']);
const SKIP_DIRS = new Set(['stitch_assets']);

async function collect(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      found.push(...(await collect(join(dir, entry.name))));
    } else if (!SKIP.has(entry.name)) {
      found.push(join(dir, entry.name));
    }
  }
  return found;
}

async function main() {
  const files = (await collect(WWW)).sort();
  const hash = createHash('sha256');
  for (const file of files) hash.update(await readFile(file));
  const version = hash.digest('hex').slice(0, 12);

  const assets = files.map((f) => `./${relative(WWW, f)}`);
  // The start URL is what a launched PWA actually requests.
  assets.unshift('./');

  const source = `// Generated by tools/make-sw.mjs — do not edit by hand.
// Regenerate with \`npm run build:sw\` after changing anything in assets/www.

const CACHE = 'shopnest-${version}';
const ASSETS = ${JSON.stringify(assets, null, 2).replace(/\n/g, '\n')};

// Everything the app needs is in this list, so installation either takes the whole
// bundle or fails and leaves the previous version serving.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first: the bundle is versioned, so a hit is never stale — a new deploy
// arrives as a new cache name rather than as a fresher copy of an old file.
self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // signalling and peers

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).catch(() => {
        // An offline navigation to any route still gets the app shell.
        if (request.mode === 'navigate') return caches.match('./');
        throw new Error('offline and not cached: ' + url.pathname);
      });
    })
  );
});
`;

  await writeFile(SW, source);
  console.log(`sw.js: ${assets.length} entries, cache shopnest-${version}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
